/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face.template.ide;


/**
 * Use this class to register ide components.
 */
public class TemplateIdeModule extends AbstractTemplateIdeModule {
}
