/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face.template.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TemplateUiModule extends AbstractTemplateUiModule {

	public TemplateUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
