/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face.template.formatting2

import com.epistimis.face.template.services.TemplateGrammarAccess
import com.epistimis.face.template.template.TemplateSpecification
import com.epistimis.face.template.template.UsingExternalTemplateStatement
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class TemplateFormatter extends AbstractFormatter2 {
	
	@Inject extension TemplateGrammarAccess

	def dispatch void format(TemplateSpecification templateSpecification, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (usingExternalTemplateStatement : templateSpecification.usingExternalTemplateStatement) {
			usingExternalTemplateStatement.format
		}
		for (structuredTemplateElementTypeDecl : templateSpecification.structuredTemplateElementTypeDecl) {
			structuredTemplateElementTypeDecl.format
		}
	}

	def dispatch void format(UsingExternalTemplateStatement usingExternalTemplateStatement, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		usingExternalTemplateStatement.externalTemplateTypeReference.format
	}
	
	// TODO: implement for MainEntityTypeTemplateMethodDecl, OptionalEntityTypeTemplateMethodParameterList, MainEquivalentEntityTypeTemplateMethodDecl, SupportingEntityTypeTemplateMethodDecl, SupportingEquivalentEntityTypeTemplateMethodDecl, EntityTypeTemplateMethodBody, EquivalentEntityTypeTemplateMethodDecl, EquivalentEntityTypeTemplateMethodParameterList, EquivalentEntityTypeTemplateMethodBody, EquivalentEntityTypeTemplateMethodMember, EquivalentEntityTypeTemplateElementMemberStatement, UnionTypeDecl, UnionBody, UnionSwitchStatement, UnionSwitchBody, CaseExpression, CaseLabel, UnionMember, EntityTypeStructuredTemplateElementMember, ExplicitDesignatedEntityNonEntityTypeCharacteristicReferenceExpression, StructuredTemplateElementTypeReferenceStatement, StructuredTemplateElementTypeReferenceExpression, StructuredTemplateElementTypeReferenceParameterList, StructuredTemplateElementTypeReferenceParameter, EntityTypeStructuredTemplateElementDeclaredParameterExpression, DesignatedEquivalentEntityNonEntityTypeCharacteristicReference, DesignatedEntityNonEntityTypeCharacteristicReference, DesignatedEntityNonEntityTypeCharacteristicWildcardReference, DesignatedEntityEnumerationTypeCharacteristicReference, DesignatedEntityTypeReferencePath, ExplicitEntityTypeReferenceJoinPath, QualifiedEntityTypeReference, EnumLiteralReferenceExpression
}
