/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face.template;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TemplateStandaloneSetup extends TemplateStandaloneSetupGenerated {

	public static void doSetup() {
		new TemplateStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
